# Generated by Django 2.2.3 on 2020-08-31 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('comment', models.CharField(max_length=200, verbose_name='コメント')),
                ('post_dt', models.DateTimeField(verbose_name='投稿日')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
